# Generated by Django 4.2 on 2026-09-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='نام و نام خانوادگی')),
                ('designation', models.CharField(default='Chef', max_length=120, verbose_name='سمت')),
                ('image', models.ImageField(default='team/default.jpg', upload_to='team/', verbose_name='تصویر')),
                ('facebook', models.URLField(blank=True, default='', verbose_name='فیسبوک')),
                ('twitter', models.URLField(blank=True, default='', verbose_name='توییتر')),
                ('instagram', models.URLField(blank=True, default='', verbose_name='اینستاگرام')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سرآشپز',
                'verbose_name_plural': 'تیم سرآشپزها',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان عضویت')),
            ],
            options={
                'verbose_name': 'عضو خبرنامه',
                'verbose_name_plural': 'خبرنامه',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیح')),
                ('icon', models.CharField(default='fa-utensils', help_text='مثلا: fa-user-tie یا fa-cart-plus', max_length=80, verbose_name='کلاس آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Restoran', max_length=120, verbose_name='نام رستوران')),
                ('address', models.CharField(default='123 Street, New York, USA', max_length=255, verbose_name='آدرس')),
                ('phone', models.CharField(default='+012 345 67890', max_length=50, verbose_name='تلفن')),
                ('email', models.EmailField(default='info@example.com', max_length=254, verbose_name='ایمیل')),
                ('booking_email', models.EmailField(default='book@example.com', max_length=254, verbose_name='ایمیل رزرو')),
                ('tech_email', models.EmailField(default='tech@example.com', max_length=254, verbose_name='ایمیل پشتیبانی')),
                ('open_weekdays', models.CharField(default='09AM - 09PM', max_length=100, verbose_name='ساعت کاری شنبه تا پنجشنبه')),
                ('open_weekend', models.CharField(default='10AM - 08PM', max_length=100, verbose_name='ساعت کاری جمعه')),
                ('facebook', models.URLField(blank=True, default='', verbose_name='فیسبوک')),
                ('twitter', models.URLField(blank=True, default='', verbose_name='توییتر')),
                ('instagram', models.URLField(blank=True, default='', verbose_name='اینستاگرام')),
                ('youtube', models.URLField(blank=True, default='', verbose_name='یوتیوب')),
                ('map_embed', models.TextField(blank=True, default='', verbose_name='کد embed نقشه')),
            ],
            options={
                'verbose_name': 'اطلاعات سایت',
                'verbose_name_plural': 'اطلاعات سایت',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120, verbose_name='نام مشتری')),
                ('profession', models.CharField(blank=True, default='', max_length=120, verbose_name='شغل')),
                ('message', models.TextField(verbose_name='متن نظر')),
                ('image', models.ImageField(default='testimonial/default.jpg', upload_to='testimonial/', verbose_name='تصویر')),
                ('active', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
            ],
            options={
                'verbose_name': 'نظر مشتری',
                'verbose_name_plural': 'نظرات مشتریان',
                'ordering': ['-created_time'],
            },
        ),
    ]
