# Generated by Django 4.2 on 2026-09-17 13:20

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='نام')),
                ('label', models.CharField(default='Popular', help_text='متن کوچک بالای نام تب، مثل Popular یا Special', max_length=60, verbose_name='برچسب کوچک')),
                ('icon', models.CharField(default='fa-utensils', help_text='مثلا: fa-coffee یا fa-hamburger', max_length=80, verbose_name='کلاس آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='نام غذا')),
                ('description', models.TextField(verbose_name='توضیح کوتاه')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت')),
                ('image', models.ImageField(default='menu/default.jpg', upload_to='menu/', verbose_name='تصویر')),
                ('meal', models.CharField(choices=[('breakfast', 'صبحانه'), ('lunch', 'ناهار'), ('dinner', 'شام')], default='dinner', max_length=20, verbose_name='وعده')),
                ('is_special', models.BooleanField(default=False, verbose_name='پیشنهاد ویژه')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.category', verbose_name='دسته\u200cبندی')),
                ('tag', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='برچسب\u200cها')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذاها',
                'ordering': ['-created_time'],
            },
        ),
    ]
